In [4]:
import numpy as np

In [11]:
%timeit [j**4 for j in range(1, 9)]

1.2 µs ± 104 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [12]:
%timeit np.arange(1, 9)**4

3.03 µs ± 332 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [13]:
x = np.array([1, 2, 3, 4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [14]:
x = [1, 2, 3, 4, 5]
y = np.array(x)
print(y)
y

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [16]:
l = []
for i in range(1, 5):
    int_1 = input("enter :")
    l.append(int_1)

print(np.array(l))

['1' '2' '3' '4']


In [15]:
l = []
for i in range(1, 5):
    int_1 = int(input("enter :"))
    l.append(int_1)

print(np.array(l))

[1 2 3 4]


In [17]:
x = np.array([1, 2, 3, 4])
print(x)
print(x.ndim)

[1 2 3 4]
1


In [18]:
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [20]:
ar2 = np.array([[1,2,3,4],[1,2,3]])
print(ar2)
print(ar2.ndim)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [24]:
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [27]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [30]:
ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [32]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


In [33]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [34]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
ar_dia1 = np.eye(3,5)
print(ar_dia1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [40]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]


In [42]:
var = np.random.rand(4)
print(var)

[0.26088381 0.7016434  0.14095849 0.90425329]


In [44]:
var1 = np.random.rand(2,5)
print(var1)

[[0.84971251 0.17730892 0.08411812 0.86503009 0.64190893]
 [0.21365244 0.59376674 0.11310859 0.30039395 0.58159215]]


In [46]:
var2 = np.random.randn(5)
print(var2)

[-2.57011425 -0.23540333  1.30182569 -0.01014825 -0.37240097]


In [49]:
var3 = np.random.ranf(4)
print(var3)

[0.0750272  0.75162902 0.65638299 0.85518733]


In [50]:
var4 = np.random.randint(5,20,5)
print(var4)

[ 7 10  5  8 12]


In [53]:
var5 = np.array([1,2,3,4,12,13,14,15])
print("Data Type: ", var5.dtype)

Data Type:  int32


In [54]:
var6 = np.array([1.0,1.2,1.3])
print("Data Type: ", var6.dtype)

Data Type:  float64


In [55]:
var7 = np.array(["A","S","D","F"])
print("Data Type: ", var7.dtype)

Data Type:  <U1


In [56]:
var8 = np.array(["A","S","D","F",1,2,3,4])
print("Data Type: ", var8.dtype)

Data Type:  <U11


In [63]:
x = np.array([1,2,3,4])
y = np.array([1,2,3,4],dtype = np.int8)
z = np.array([1,2,3,4],dtype = "f")
new = np.float32(x)
new_one = np.int_(new)
new1 = x.astype(float)
print(x)
print("Data Type: ", x.dtype)
print(y)
print("Data Type: ", y.dtype)
print(z)
print("Data Type: ", z.dtype)
print(new)
print("Data Type: ", new.dtype)
print(new_one)
print("Data Type: ", new_one.dtype)
print(new1)
print("Data Type: ", new1.dtype)

[1 2 3 4]
Data Type:  int32
[1 2 3 4]
Data Type:  int8
[1. 2. 3. 4.]
Data Type:  float32
[1. 2. 3. 4.]
Data Type:  float32
[1 2 3 4]
Data Type:  int32
[1. 2. 3. 4.]
Data Type:  float64


In [64]:
var = np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [65]:
var1 = np.array([1,2,3,4], ndmin = 4)

print(var1)
print()
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]

4

(1, 1, 1, 4)


In [69]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)
x = var2.reshape(3,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]
1
[[1 2]
 [3 4]
 [5 6]]
2


In [73]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
x1 = var3.reshape(2,3,2)
print(x1)
print(x1.ndim)
one = x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [85]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
varadd = var1 + 3
varadd1 = var1 + var2
varadd2 = np.add(var1, var2)
varsubstract = var1 - 3
varmultiply = var1 * 3
vardivide = var1 / 3
varmod = var1 % 3
varreciprocal = np.reciprocal(var1)
print(varadd)
print(varadd1)
print(varadd2)
print(varsubstract)
print(varmultiply)
print(vardivide)
print(varmod)
print(varreciprocal)

[4 5 6 7]
[2 4 6 8]
[2 4 6 8]
[-2 -1  0  1]
[ 3  6  9 12]
[0.33333333 0.66666667 1.         1.33333333]
[1 2 0 1]
[1 0 0 0]


In [87]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
varadd = var1 + 3
varadd1 = var1 + var2
varadd2 = np.add(var1, var2)
varsubstract = var1 - 3
varmultiply = var1 * 3
varmultiply1 = var1 * var2
vardivide = var1 / 3
varmod = var1 % 3
varreciprocal = np.reciprocal(var1)
print(varadd)
print(varadd1)
print(varadd2)
print(varsubstract)
print(varmultiply)
print(varmultiply1)
print(vardivide)
print(varmod)
print(varreciprocal)

[[4 5 6 7]
 [4 5 6 7]]
[[2 4 6 8]
 [2 4 6 8]]
[[2 4 6 8]
 [2 4 6 8]]
[[-2 -1  0  1]
 [-2 -1  0  1]]
[[ 3  6  9 12]
 [ 3  6  9 12]]
[[ 1  4  9 16]
 [ 1  4  9 16]]
[[0.33333333 0.66666667 1.         1.33333333]
 [0.33333333 0.66666667 1.         1.33333333]]
[[1 2 0 1]
 [1 2 0 1]]
[[1 0 0 0]
 [1 0 0 0]]


In [96]:
var = np.array([3,2,1,4,5,3,2])
print("Min : ",np.min(var),np.argmin(var))
print("Max : ",np.max(var),np.argmax(var))
print("Sqrt : ",np.sqrt(var))
print(np.sin(var))
print(np.cos(var))
print(np.cumsum(var))

Min :  1 2
Max :  5 4
Sqrt :  [1.73205081 1.41421356 1.         2.         2.23606798 1.73205081
 1.41421356]
[ 0.14112001  0.90929743  0.84147098 -0.7568025  -0.95892427  0.14112001
  0.90929743]
[-0.9899925  -0.41614684  0.54030231 -0.65364362  0.28366219 -0.9899925
 -0.41614684]
[ 3  5  6 10 15 18 20]


In [91]:
var1 = np.array([[2,1,3],[9,5,6]])
print("Min : ",np.min(var1,axis=1),np.min(var1,axis=0))
print("Max : ",np.max(var1,axis=1),np.max(var1,axis=0))

Min :  [1 5] [2 1 3]
Max :  [3 9] [9 5 6]


In [97]:
# broadcast error if array size not same
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3])
print(var1 + var2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [99]:
var1 = np.array([1,2,3])
var2 = np.array([[1],[2],[3]])
print(var1 + var2)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [100]:
var = np.array([9,8,7,6])
print(var[1])
print(var[-3])

8
8


In [102]:
var1 = np.array([[9,8,7],[4,5,6]])
print(var1)
print(var1.ndim)
print(var1[0,2])

[[9 8 7]
 [4 5 6]]
2
7


In [104]:
var2 = np.array([[[1,2],[6,7]]])
print(var2)
print(var2.ndim)
print(var2[0,1,1])

[[[1 2]
  [6 7]]]
3
7


In [110]:
var2 = np.array([[[1,2],[3,4]],[[6,7],[8,9]]])
print(var2)
print(var2.ndim)
print(var2[1,0,1])

[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]
3
7


In [118]:
var = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
print(var)
print(var[1,1:])
print(var[2,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]
[8 7 6 5]
[12 13 14 15]


In [119]:
var = np.array([9,8,7,6,5,4])
print(var)
for i in var:
    print(i)

[9 8 7 6 5 4]
9
8
7
6
5
4


In [121]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
for j in var1:
    print(j)
for k in var1:
    for l in k:
        print(l)

[[1 2 3 4]
 [1 2 3 4]]
[1 2 3 4]
[1 2 3 4]
1
2
3
4
1
2
3
4


In [122]:
var3 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(var3)
for j in var3:
    print(j)
for k in var3:
    for l in k:
        print(l)
for a in var3:
    for b in a:
        for c in b:
            print(c)

[[[1 2 3 4]
  [1 2 3 4]]]
[[1 2 3 4]
 [1 2 3 4]]
[1 2 3 4]
[1 2 3 4]
1
2
3
4
1
2
3
4


In [126]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print(var3.ndim)
for i in np.nditer(var3):
    print(i)
for i in np.nditer(var3,flags=['buffered'],op_dtypes=["S"]):
    print(i)
for i,d in np.ndenumerate(var3):
    print(i,d)

[[[9 8 7 6]
  [1 2 3 4]]]
3
9
8
7
6
1
2
3
4
b'9'
b'8'
b'7'
b'6'
b'1'
b'2'
b'3'
b'4'
(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


In [129]:
var = np.array([1,2,3,4])
co = var.copy()
vi = var.view()
var[1] = 40
print(var)
print(co)
print(vi)

[ 1 40  3  4]
[1 2 3 4]
[ 1 40  3  4]


In [133]:
var1 = np.array([1,2,3,4])
var2 = np.array([9,8,7,6])
ar = np.concatenate((var1,var2))
print(ar)

[1 2 3 4 9 8 7 6]


In [137]:
var1 = np.array([[1,2],[3,4]])
var2 = np.array([[9,8],[7,6]])
ar = np.concatenate((var1,var2))
ar1 = np.concatenate((var1,var2),axis=1)
ar2 = np.concatenate((var1,var2),axis=0)
print(var1)
print(var2)
print(ar)
print(ar1)
print(ar2)

[[1 2]
 [3 4]]
[[9 8]
 [7 6]]
[[1 2]
 [3 4]
 [9 8]
 [7 6]]
[[1 2 9 8]
 [3 4 7 6]]
[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [141]:
var1 = np.array([1,2,3,4])
var2 = np.array([9,8,7,6])
ar = np.stack((var1,var2))
ar1 = np.stack((var1,var2),axis=1)
ar2 = np.stack((var1,var2),axis=0)
ar3 = np.hstack((var1,var2)) #row
ar4 = np.vstack((var1,var2)) #col
ar5 = np.dstack((var1,var2)) #height
print(var1)
print(var2)
print(ar)
print(ar1)
print(ar2)
print(ar3)
print(ar4)
print(ar5)

[1 2 3 4]
[9 8 7 6]
[[1 2 3 4]
 [9 8 7 6]]
[[1 9]
 [2 8]
 [3 7]
 [4 6]]
[[1 2 3 4]
 [9 8 7 6]]
[1 2 3 4 9 8 7 6]
[[1 2 3 4]
 [9 8 7 6]]
[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


In [145]:
var = np.array([1,2,3,4,5,6])
print(var)
ar = np.array_split(var,3)
print(ar)
print(type(ar))
print(ar[0])

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
<class 'list'>
[1 2]


In [150]:
var = np.array([[1,2],[3,4],[5,6]])
print(var)
ar = np.array_split(var,3)
ar1 = np.array_split(var,3,axis=1)
print(ar)
print(type(ar))
print(ar[0])
print(ar1)

[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]
<class 'list'>
[[1 2]]
[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int32)]


In [154]:
var = np.array([4,2,3,4,2,5,2,5,6,7])
x = np.where((var%2) == 0)
print(x) 

(array([0, 1, 3, 4, 6, 8], dtype=int64),)


In [16]:
var = np.array([1,2,3,4,6,7,8,9,10])
#x = np.searchsorted(var,5)
x1 = np.searchsorted(var,5,side="right")
#print(x)
print(x1)

4


In [19]:
var = np.array([1,2,3,4,9,10])
x = np.searchsorted(var,[5,6,7])
x1 = np.searchsorted(var,[5,6,7],side="right")
print(x)
print(x1)

[4 4 4]
[4 4 4]


In [20]:
var = np.array([4,2,3,1,12,5,22,52,6,7])
print(np.sort(var))

[ 1  2  3  4  5  6  7 12 22 52]


In [21]:
var = np.array(["a","s","d","f"])
print(np.sort(var))

['a' 'd' 'f' 's']


In [23]:
var = np.array([[4,2,3],[1,12,5],[22,52,6]])
print(np.sort(var))

[[ 2  3  4]
 [ 1  5 12]
 [ 6 22 52]]


In [25]:
var = np.array(["a","s","d","f"])
f = [True,False,False,True]
new_a = var [f]
print(new_a)
print(type(new_a))

['a' 'f']
<class 'numpy.ndarray'>


In [34]:
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[5 4 2 1 3]


In [37]:
var = np.array([1,2,3,4,2,5,2,6,2,7])
x = np.unique(var,return_index=True,return_counts=True)
print(x)

(array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 9], dtype=int64), array([1, 4, 1, 1, 1, 1, 1], dtype=int64))


In [39]:
var = np.array([1,2,3,4,5,6])
y = np.resize(var,(2,3))
y1 = np.resize(var,(3,2))
print(y)
print(y1)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [46]:
var = np.array([1,2,3,4,5,6])
y = np.resize(var,(2,3))
y1 = np.resize(var,(3,2))
print(y)
print(y.flatten())
print(y1)
print(y1.flatten())
print(y1.flatten(order="F"))
print(y1.flatten(order="C"))
print(np.ravel(y))
print(np.ravel(y,order="F"))
print(np.ravel(y,order="C"))
print(np.ravel(y,order="A"))
print(np.ravel(y,order="K"))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 3 5 2 4 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 4 2 5 3 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [58]:
var = np.array([1,2,3,4])
print(var)
v = np.insert(var,2,40)
print(v)
v1 = np.insert(var,(2,4),40)
print(v1)
v2 = np.insert(var,(2,4),6.5)
print(v2)
v3 = np.append(var,6.5)
print(v3)

[1 2 3 4]
[ 1  2 40  3  4]
[ 1  2 40  3  4 40]
[1 2 6 3 4 6]
[1.  2.  3.  4.  6.5]


In [63]:
var = np.array([[1,2,3],[1,2,3]])
print(var)
v = np.insert(var,2,40,axis=0)
v3 = np.insert(var,2,40,axis=1)
print(v)
print(v3)
v4 = np.insert(var,2,[22,23,24],axis=0)
v5 = np.insert(var,2,[22,23],axis=1)
print(v4)
print(v5)
v6 = np.append(var,[[45,44,23]],axis=0)
print(v6)


[[1 2 3]
 [1 2 3]]
[[ 1  2  3]
 [ 1  2  3]
 [40 40 40]]
[[ 1  2 40  3]
 [ 1  2 40  3]]
[[ 1  2  3]
 [ 1  2  3]
 [22 23 24]]
[[ 1  2 22  3]
 [ 1  2 23  3]]
[[ 1  2  3]
 [ 1  2  3]
 [45 44 23]]


In [64]:
var = np.array([1,2,3,4])
print(var)
d = np.delete(var,2)
print(d)

[1 2 3 4]
[1 2 4]


In [69]:
var = np.matrix([[1,2],[1,2]])
var1 = np.matrix([[1,2],[1,2 ]])
print(var)
print(type(var))
print(var*var1)
print(var.dot(var1))

[[1 2]
 [1 2]]
<class 'numpy.matrix'>
[[3 6]
 [3 6]]
[[3 6]
 [3 6]]


In [76]:
var = np.matrix([[1,2,3],[4,5,6]])
print(var)
print(np.transpose(var))
print(var.T)
print(np.swapaxes(var,0,1))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [81]:
var = np.matrix([[1,2],[3,4]])
print(var)
print(np.swapaxes(var,0,1))
print(np.linalg.inv(var))
print(np.linalg.matrix_power(var,2))
print(np.linalg.matrix_power(var,0))
print(np.linalg.matrix_power(var,-2))
print(np.linalg.det(var))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 7 10]
 [15 22]]
[[1 0]
 [0 1]]
[[ 5.5  -2.5 ]
 [-3.75  1.75]]
-2.0000000000000004
